# Generated by Django 3.2 on 2022-06-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gig_venue'),
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='gig',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlist_gig', to='home.gig'),
        ),
    ]
