# Generated by Django 3.2 on 2022-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
