# Generated by Django 3.2 on 2022-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0002_gig_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setlist.venue'),
        ),
    ]
