# Generated by Django 3.2 on 2022-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0003_gig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='song',
            field=models.ManyToManyField(to='setlist.Song'),
        ),
    ]
