# Generated by Django 3.2 on 2022-05-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0005_auto_20220516_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlist',
            old_name='user',
            new_name='author',
        ),
    ]
