# Generated by Django 3.2 on 2022-05-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0008_auto_20220517_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='likes',
        ),
    ]
