# Generated by Django 3.2 on 2022-05-18 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlist', '0009_remove_setlist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='song',
        ),
        migrations.AddField(
            model_name='release',
            name='songs',
            field=models.ManyToManyField(related_name='releases', to='setlist.Song'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='agree',
            field=models.ManyToManyField(related_name='setlist_agreed', to=settings.AUTH_USER_MODEL),
        ),
    ]
