# Generated by Django 3.2 on 2022-05-20 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlist', '0010_auto_20220518_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='agree',
            field=models.ManyToManyField(blank=True, related_name='setlist_agreed', to=settings.AUTH_USER_MODEL),
        ),
    ]
