# Generated by Django 3.2 on 2022-05-20 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlist', '0011_alter_setlist_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='disagree',
            field=models.ManyToManyField(blank=True, related_name='setlist_disagree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='agree',
            field=models.ManyToManyField(blank=True, related_name='setlist_agree', to=settings.AUTH_USER_MODEL),
        ),
    ]
