# Generated by Django 3.2 on 2022-06-10 13:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
