# Generated by Django 3.2 on 2022-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gig_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='featured_image_status',
            field=models.IntegerField(choices=[(0, 'Waiting Confirmation'), (1, 'Published')], default=0),
        ),
    ]
