# Generated by Django 3.2 on 2022-06-13 11:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gig_featured_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='featured_image_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Waiting Confirmation'), (1, 'Published')], default=0, null=True),
        ),
    ]
